# Generated by Django 3.2.9 on 2021-12-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=60)),
                ('subInventario', models.CharField(max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=60)),
                ('estoque', models.IntegerField()),
                ('udm', models.CharField(max_length=2)),
                ('custoUnitario', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
