# Generated by Django 3.2.9 on 2021-12-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('idSubInventario', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('descricao', models.CharField(max_length=300)),
                ('subInventario', models.CharField(max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=60)),
                ('estoque', models.DecimalField(decimal_places=2, max_digits=7)),
                ('udm', models.CharField(max_length=3)),
                ('custoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
