# Generated by Django 3.2.9 on 2021-12-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='idSubInventario',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
