# Generated by Django 3.2.9 on 2021-12-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_item_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='udm',
            field=models.CharField(max_length=3),
        ),
    ]
