# Generated by Django 3.2.9 on 2021-12-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_item_udm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='custoUnitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='estoque',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
